[build]
  # Build command - what Netlify runs to build your site
  command = "npm run build"
  
  # Publish directory - where Netlify serves files from
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Single Page Application redirects
# This ensures all routes work properly in React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self';"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent indexing of source maps
[[headers]]
  for = "*.map"
  [headers.values]
    X-Robots-Tag = "noindex"
